---
- name: Add bash aliases to zsh
  ansible.builtin.lineinfile:
    path: "/home/{{ target_user }}/.zshrc"
    line: alias {{ alias.key }}="{{ alias.value }}"
    insertafter: "^# Other aliases$"
    mode: '0640'
    create: true
  loop: "{{ shell_aliases | dict2items }}"
  loop_control:
    loop_var: alias
    label: alias.name
