---
- name: Install Oh My Posh
  ansible.builtin.shell:
    cmd: set -o pipefail && curl -s https://ohmyposh.dev/install.sh | bash -s
    executable: /bin/bash
    creates: "/home/{{ target_user }}/bin/oh-my-posh"
  changed_when: true

- name: Add Oh My Posh configuration
  ansible.builtin.copy:
    src: files/oh-my-posh.toml
    dest: "/home/{{ target_user }}/.config/zsh/oh-my-posh.toml"
    mode: '0644'

- name: Remove any non-final occurrences of oh-my-posh init line from the shells
  ansible.builtin.lineinfile:
    path: "{{ shell }}"
    line: eval "$(oh-my-posh init bash --config /home/{{ target_user }}/.config/zsh/oh-my-posh.toml)"
    state: absent
    mode: '0644'
  loop:
    - "/home/{{ target_user }}/.bashrc"
    - "/home/{{ target_user }}/.zshrc"
  loop_control:
    loop_var: shell

- name: Ensure oh-my-posh init line is the last line in .zshrc
  ansible.builtin.lineinfile:
    path: "{{ item.value }}"
    line: eval "$(oh-my-posh init {{ item.key }} --config /home/{{ target_user }}/.config/zsh/oh-my-posh.toml)"
    insertafter: EOF
    mode: '0644'
  with_dict:
    - {"bash": "/home/{{ target_user }}/.bashrc"}
    - {"zsh": "/home/{{ target_user }}/.zshrc"}
