---
- name: Install vim
  ansible.builtin.apt:
    name: vim

- name: Install zsh
  ansible.builtin.apt:
    name: zsh

- name: Set zsh as default command for {{ USER }}
  ansible.builtin.user:
    name: "{{ USER }}"
    shell: /usr/bin/zsh

- name: Prepare Oh My zsh
  ansible.builtin.import_tasks: prepare_omzsh.yml

- name: Prepare Powerlvl10k
  ansible.builtin.import_tasks: prepare_powerlvl10k.yml

- name: Add zsh plugins
  ansible.builtin.import_tasks: add_zsh_plugins.yml

- name: Do personal configurations
  ansible.builtin.import_tasks: personal_configurations.yml
