---
- name: Install Homebrew
  ansible.builtin.import_tasks: install_homebrew.yml

- name: Prepare zsh
  ansible.builtin.import_tasks: prepare_zsh.yml

- name: Install plugins
  ansible.builtin.import_tasks: install_plugins.yml

- name: Prepare tmux
  ansible.builtin.import_tasks: prepare_tmux.yml
