---
- name: Basic shell preparations
  ansible.builtin.import_tasks: basic_installations.yml

- name: Prepare Oh My zsh
  ansible.builtin.import_tasks: prepare_omzsh.yml

- name: Prepare Powerlvl10k
  ansible.builtin.import_tasks: prepare_powerlvl10k.yml

- name: Add zsh plugins
  ansible.builtin.import_tasks: add_zsh_plugins.yml

- name: Set up personal configurations
  ansible.builtin.import_tasks: personal_configurations.yml
