---
- name: Install 'powerlevel10k'
  ansible.builtin.git:
    repo: https://github.com/romkatv/powerlevel10k.git
    dest: "/home/{{ target_user }}/.oh-my-zsh/custom/themes/powerlevel10k"
    version: v1.19.0
    depth: 1

- name: Configure zsh to use 'powerlevel10k'
  ansible.builtin.lineinfile:
    path: "/home/{{ target_user }}/.zshrc"
    regexp: ZSH_THEME=
    line: ZSH_THEME="powerlevel10k/powerlevel10k"
