---
- name: Download script to install 'Oh My Zsh'
  ansible.builtin.uri:
    url: https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh
    dest: /tmp/oh-my-zsh-install.sh
    mode: "0755"
    creates: /tmp/oh-my-zsh-install.sh

- name: Install 'Oh My Zsh' # noqa: partial-become[task]
  become_user: "{{ TARGET_USER }}"
  ansible.builtin.shell:
    cmd: set -o pipefail && echo y | /tmp/oh-my-zsh-install.sh
    creates: "/home/{{ TARGET_USER }}/.oh-my-zsh"
    executable: /bin/bash

- name: Set zsh as case sensitive
  ansible.builtin.lineinfile:
    path: "/home/{{ TARGET_USER }}/.zshrc"
    regexp: ^.*CASE_SENSITIVE=.*$
    line: CASE_SENSITIVE="true"

- name: Add block of configuration
  ansible.builtin.blockinfile:
    path: "/home/{{ TARGET_USER }}/.zshrc"
    block: |
      # Ansible managed
      setopt ksharrays
