# Sources:
#   https://github.com/JanDeDobbeleer/oh-my-posh/blob/main/themes/thecyberden.omp.json
#   https://www.youtube.com/watch?v=9U8LCjuQzdc

version = 2
console_title_template = '{{ .Folder }}'

# Left side blocks
[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    type = 'session'
    style = 'diamond'
    leading_diamond = ''
    template = '  {{ .HostName }} '
    background = 'p:blue'
    foreground = 'p:white'

  [[blocks.segments]]
    type = 'path'
    style = 'diamond'
    trailing_diamond = ""
    template = '<parentBackground></>  {{ .Path }} ' #         nf-ple https://www.nerdfonts.com/cheat-sheet
    background = 'p:yellow'
    foreground = 'p:black'

    [blocks.segments.properties]
      style = 'full'

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    type = 'root'
    style = 'plain'
    template = ' '
    foreground = 'red'

  [[blocks.segments]]
    type = 'text'
    style = 'plain'
    template = ' '
    foreground_templates = [
        "{{if gt .Code 0}}red{{end}}",
        "{{if eq .Code 0}}magenta{{end}}",
    ]

[transient_prompt]
    background = 'transparent'
    template = ' '
    foreground_templates = [
        "{{if gt .Code 0}}red{{end}}",
        "{{if eq .Code 0}}magenta{{end}}",
    ]

# Tooltips
[[tooltips]]
type = "git"
tips = [ "git", "g"  ]
style = "diamond"
foreground = "p:white"
background = "p:blue"
leading_diamond = ""
trailing_diamond = ""
template = ' {{ .UpstreamIcon }}{{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Working.Changed }}  {{ .Working.String }}{{ end }}{{ if and (.Working.Changed) (.Staging.Changed) }} |{{ end }}{{ if .Staging.Changed }}  {{ .Staging.String }}{{ end }}{{ if gt .StashCount 0 }}  {{ .StashCount }}{{ end }} '

  [tooltips.properties]
    fetch_status = true
    fetch_upstream_icon = true

[[tooltips]]
type = 'kubectl'
tips = [ "kubectl", "k"  ]
style = "diamond"
foreground = "p:white"
background = "p:blue"
leading_diamond = ""
trailing_diamond = ""
template = " 󱃾 {{.Context}}"

[[tooltips]]
type = "go"
tips = [ "go" ]
style = "diamond"
foreground = "p:white"
background = "p:blue"
leading_diamond = ""
trailing_diamond = ""
template = "  {{ .Full }} "

# Colors
[palette]
white = '#ffffff'
black = '#193549'
orange = '#FF6B00' # '#ff2a00'
blue = '#0021FF' #'#6B00FF' '#2A00ff'
yellow = '#FFDE00'
