# Source: https://www.youtube.com/watch?v=ud7YxC33Z3w

ZINIT_HOME="${XDG_DATA_HOME:-${HOME}/.local/share}/zinit/zinit.git"

if [ ! -d "${ZINIT_HOME}" ]; then
    mkdir -p "$(dirname ${ZINIT_HOME})"
    git clone https://github.com/zdharma-continuum/zinit.git "${ZINIT_HOME}"
fi

source "${ZINIT_HOME}/zinit.zsh"

# Install zsh plugins using zinit
zinit ice depth=1; zinit light zsh-users/zsh-syntax-highlighting
zinit ice depth=1; zinit light zsh-users/zsh-completions
zinit ice depth=1; zinit light zsh-users/zsh-autosuggestions
zinit ice depth=1; zinit light Aloxaf/fzf-tab

# Select autoslection using ctrl + e
bindkey -e
# Move in history search using ctrl + p/n
bindkey '^p' history-search-backward
bindkey '^n' history-search-forward

bindkey '\e[1;5C' forward-word  # Ctrl + Right Arrow
bindkey '\e[1;5D' backward-word # Ctrl + Left Arrow

HISTSIZE=5000
HISTFILE=~/.zsh_history
SAVEHIST=${HISTSIZE}
HISTDUP=erase
setopt appendhistory
setopt sharehistory # Share history between shells
setopt hist_ignore_space # Add space before command to prevent it from being registered in the history
# Ignore duplicates
setopt hist_ignore_all_dups
setopt hist_save_no_dups
setopt hist_ignore_dups
setopt hist_find_no_dups

# Completion styling
zstyle ':completion:*' list-colors "${(s.:.)LS_COLORS}"
zstyle ':completion:*' menu no
zstyle ':fzf-tab:complete:cd:*' fzf-preview 'ls --color $realpath'
zstyle ':fzf-tab:complete:__zoxide_z:*' fzf-preview 'ls --color $realpath'

# Add snipets
zinit snippet OMZP::git # Install oh-my-zsh plugin git
zinit snippet OMZP::sudo
zinit snippet OMZP::archlinux
zinit snippet OMZP::aws
zinit snippet OMZP::kubectl
zinit snippet OMZP::kubectx
zinit snippet OMZP::command-not-found

autoload -Uz compinit && compinit
zinit cdreplay -q # Replay on cached condition

alias ls='ls --color'

# Other aliases


source <(fzf --zsh) # Enables fuzzy finding
eval "$(zoxide init zsh)" # Enables zoxide
