---
git_aliases:
  ac: git add -A && git commit -m "$@"
  acp: git add -A && git commit -m "$@" && git push
  acpf: git add -A && git commit -m "$@" && git push --force
  adog: git log --all --decorate --oneline --graph
  st: status
  save: branch=$(git rev-parse --short HEAD); git branch -D ${branch} 2>/dev/null; git checkout -b ${branch}-save && git checkout ${branch}
