---
git_aliases:
  ac: git add -A && git commit -m "$@"
  acp: git add -A && git commit -m "$@" && git push
  acpf: git add -A && git commit -m "$@" && git push --force
  adog: git log --all --decorate --oneline --graph
  co: git checkout $1
  fr: git fetch origin $1:$1 && git rebase $1
  p: git pull
  st: status
  save: branch=$(git rev-parse --short HEAD); git branch -D ${branch} 2>/dev/null; git checkout -b ${branch}-save && git checkout ${branch}
  update-tags: git tag -l | xargs git tag --delete && git fetch --tags
