flag_shell: false
flag_kvm: false
flag_selinux: false
flag_minikube: true
flag_kubectl: true

zsh_plugins:
  - name: zsh-syntax-highlighting
    repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
    version: 0.8.0
