---
- name: Install SSH
  ansible.builtin.apt:
    name: openssh-client

- name: Create empty generic ssh config file
  ansible.builtin.copy:
    src: files/conf
    dest: "/home/{{ target_user }}/.ssh/config"
    mode: u+rw
    force: false
