---
- name: Install SSH
  ansible.builtin.apt:
    name: openssh-client

- name: Create .ssh directory
  ansible.builtin.file:
    path: "/home/{{ target_user }}/.ssh"
    owner: "{{ target_user }}"
    group: "{{ target_user }}"
    mode: '0755'
    state: directory
  become: true
  become_user: "{{ target_user }}"

- name: Create empty generic ssh config file
  ansible.builtin.copy:
    src: files/conf
    dest: "/home/{{ target_user }}/.ssh/config"
    mode: u+rw
    force: false
  become: true
  become_user: "{{ target_user }}"
