---
- name: Restart libvirtd
  ansible.builtin.service:
    name: libvirtd
    state: restarted
    enabled: true

- name: Apply netplan
  ansible.builtin.command: # noqa: no-changed-when
    cmd: netplan apply
  async: 45
  poll: 0
