---
- name: Prepare
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl

- name: Install kubectl # noqa: command-instead-of-module
  ansible.builtin.shell:
    cmd: |
      curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
      install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
    creates: /usr/local/bin/kubectl
