---
- name: Install mux
  ansible.builtin.apt:
    name: tmux

- name: Add tmux configuration
  ansible.builtin.copy:
    source: files/tmux.conf
    target: "/home/{{ target_user }}/.tmux.conf"
    mode: '0644'
