---
- name: Install mux
  ansible.builtin.apt:
    name: tmux

- name: Add tmux configuration
  ansible.builtin.copy:
    src: files/tmux.conf
    dest: "/home/{{ target_user }}/.tmux.conf"
    mode: '0644'
