---
- name: Ensure gitconfig file exists
  ansible.builtin.file:
    path: "/home/{{ target_user }}/.gitconfig"
    state: touch
    mode: u+rw
  changed_when: false

- name: List git aliases name # noqa: command-instead-of-module partial-become[task]
  become_user: "{{ target_user }}"
  ansible.builtin.shell:
    cmd: set -o pipefail && git config --global --list | grep alias | sed 's/alias\.\(.*\)=.*/\1/'
    executable: /bin/bash
  register: present_aliases
  ignore_errors: true
  changed_when: false

- name: Add missing git aliases # noqa: command-instead-of-module partial-become[task]
  become_user: "{{ target_user }}"
  ansible.builtin.shell:
    cmd: set -o pipefail && git config --global alias.{{ aliase.name }} '!f() { {{ aliase.command }}; }; f'
    executable: /bin/bash
  loop: "{{ git_aliases }}"
  loop_control:
    loop_var: aliase
    label: aliase.name
  when: not aliase.name in present_aliases.stdout_lines
  changed_when: present_aliases.stdout_lines == ""
