---
- name: Create vim directory
  ansible.builtin.file:
    dest: "/home/{{ target_user }}/{{ directory }}"
    owner: "{{ target_user }}"
    group: "{{ target_user }}"
    mode: '0755'
    state: directory
  loop:
    - .vim
    - .vim/autoload
  loop_control:
    loop_var: directory

- name: Install vim plug
  ansible.builtin.uri:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: "/home/{{ target_user }}/.vim/autoload/plug.vim"
    creates: "/home/{{ target_user }}/.vim/autoload/plug.vim"

- name: Add plug installation section in vimrc
  ansible.builtin.lineinfile:
    path: "/home/{{ target_user }}/.vimrc"
    line: "{{ line }}"
    create: true
    mode: '0644'
  loop:
    - call plug#begin()
    - call plug#end()
  loop_control:
    loop_var: line
