---
- name: Check processor supports virtualization
  ansible.builtin.command:  # noqa: no-changed-when
    cmd: set -o pipefail && egrep -c '(vmx|svm)' /proc/cpuinfo
    executable: /bin/bash
  register: processor_virtualized

- name: Assert processor supports virtualization
  ansible.builtin.assert:
    that:
      "{{ processor_virtualized | int | > 0 }}"

- name: Install cpu-checker
  ansible.builtin.apt:
    name: cpu-checker

- name: Check KVM virtualization enabled
  ansible.builtin.command: # noqa: no-changed-when
    cmd: kvm-ok
  register: enabled_virtualization

- name: Assert enabled virtualization
  ansible.builtin.assert:
    that: enabled_virtualization.stdout
