---
- name: Prepare basic configurations
  hosts: "{{ TARGET_HOST | default([]) }}"
  vars_files:
    - inventories/dev/default.yml
    - inventories/dev/flags.yml
  become: true
  roles:
    - role: git
      when: flag_git == true
    - role: shell
      when: flag_shell == true
    - role: ssh
      when: flag_ssh == true


- name: Prepare fancy tools
  hosts: "{{ TARGET_HOST | default([]) }}"
  vars_files:
    - inventories/dev/default.yml
    - inventories/dev/flags.yml
  become: true
  roles:
    - role: gns3
      when: flag_gns3 == true
    - role: docker
      when: (flag_docker == true)
        or (flag_gns3 == true)
        or (flag_minikube == true)
    - role: kubectl
      when: flag_kubectl == true
    - role: kvm
      when: flag_kvm == true
    - role: minikube
      when: flag_minikube == true
