---
- name: Prepare basic setup
  hosts: "{{ target_host | default([]) }}"
  roles:
    - role: git
    - role: gui
      tags:
        - never
        - install_gui
    - role: shell
    - role: vim
    - role: ssh
    - role: tmux
    - role: kubectl
    - role: kvm
      tags:
        - never
        - install_kvm
