---
- name: Prepare basic setup
  hosts: "{{ target_host | default([]) }}"
  roles:
    - role: application
    - role: shell
    # - role: vim
    - role: kubectl
    - role: kvm
      tags:
        - never
        - install_kvm
