---
- name: Install and configure vim, zsh, 'oh my zsh' and power10k
  hosts: "{{ HOSTS | default('localhost') }}"
  vars_files:
    - inventories/dev/default.yml
    - inventories/dev/flags.yml
    - inventories/dev/group_vars/workstation.yml
  become: true
  roles:
    - role: shell
      when: flag_shell == true
    - role: kvm
      when: flag_kvm == true
    - role: selinux
      when: flag_selinux == true
    - role: docker
      when: flag_minikube == true
    - role: minikube
      when: flag_minikube == true
    - role: kubectl
      when: flag_kubectl == true
