---
- name: Install and configure vim, zsh, 'oh my zsh' and power10k
  hosts: "{{ HOSTS | default('localhost') }}"
  vars_files:
    - inventories/dev/group_vars/workstation.yml
  become: true
  roles:
    - role: shell
      when: flag_shell == true


- name: Install and configure kvm (Kernel-based Virtual Machine)
  hosts: "{{ HOSTS | default('localhost') }}"
  vars_files:
    - inventories/dev/group_vars/workstation.yml
  become: true
  roles:
    - role: kvm
      when: flag_kvm == true
