---
- name: Prepare basic setup
  hosts: "{{ target_host | default([]) }}"
  become: true
  roles:
    - role: git
    - role: shell
      become_user: "{{ target_user }}"
    - role: ssh
    - role: kubectl
    - role: kvm
      tags:
        - never
        - install_kvm
