---
- name: Install and configure zsh and kvm
  hosts: "{{ HOSTS | default('localhost') }}"
  vars_files:
    - inventories/dev/group_vars/workstation.yml
  become: true
  roles:
    - role: zsh
      when: flag_zsh == true
    - role: kvm
      when: flag_kvm == true
